# server-apache direct
GET http://localhost:10081/hello

###
# server-app direct
GET http://localhost:18181/hello

###
# client-app direct
GET http://localhost:18080/hello

###
# client-app which makes internal request to server-app through server-apache
GET http://localhost:18080/request-to-server-app-via-get

###
# client-app which makes internal request to server-app through server-apache
GET http://localhost:18080/request-to-server-app-via-post